# Generated by Django 5.0.1 on 2026-02-18 23:05
# Modified: removed static date CheckConstraint (stale over time; Python-level clean() is sufficient)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status', '-created_at'], name='bookings_bo_client__85080a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['artist', 'status', 'booking_date'], name='bookings_bo_artist__0c3d57_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'status'], name='bookings_bo_booking_b730a0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        # NOTE: The booking_date_not_in_past CheckConstraint was intentionally removed.
        # A static date value in DB constraints becomes stale over time.
        # Date validation is enforced at the Python level in Booking.clean().
    ]
