# Generated by Django 5.0.1 on 2026-02-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makeupartistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='profiles.makeupartistprofile'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='profiles.makeupartistprofile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='profiles.makeupartistprofile'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='profiles.makeupartistprofile'),
        ),
        migrations.AddIndex(
            model_name='makeupartistprofile',
            index=models.Index(fields=['average_rating', '-created_at'], name='profiles_ma_average_b57373_idx'),
        ),
        migrations.AddIndex(
            model_name='makeupartistprofile',
            index=models.Index(fields=['location', 'is_available'], name='profiles_ma_locatio_c64773_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['client', '-created_at'], name='favorites_f_client__1efee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('client', 'artist')},
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['artist', 'date'], name='availabilit_artist__f89a50_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['artist', 'day_of_week', 'is_active'], name='availabilit_artist__e7b007_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['artist', 'display_order'], name='portfolio_p_artist__8a6968_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['artist', 'is_featured'], name='portfolio_p_artist__bc8fcf_idx'),
        ),
    ]
