# Generated by Django 5.0.1 on 2026-02-18 23:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the service (e.g., "Bridal Makeup Package")', max_length=200, verbose_name='service name')),
                ('description', models.TextField(help_text='Detailed description of what the service includes', verbose_name='description')),
                ('category', models.CharField(choices=[('bridal', 'Bridal Makeup'), ('editorial', 'Editorial Makeup'), ('natural', 'Natural/Everyday Makeup'), ('glam', 'Glamour Makeup'), ('sfx', 'Special Effects Makeup'), ('airbrush', 'Airbrush Makeup'), ('theatrical', 'Theatrical Makeup'), ('consultation', 'Consultation'), ('other', 'Other')], db_index=True, default='other', help_text='Category of the makeup service', max_length=20, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('duration', models.PositiveIntegerField(help_text='Service duration in minutes (15 min to 8 hours)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='duration')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this service is currently available for booking', verbose_name='active')),
                ('booking_count', models.PositiveIntegerField(default=0, help_text='Total number of times this service has been booked', verbose_name='booking count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('artist', models.ForeignKey(help_text='The makeup artist offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.makeupartistprofile')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'is_active'], name='services_se_artist__808b9c_idx'), models.Index(fields=['category', 'is_active'], name='services_se_categor_d8f4e5_idx'), models.Index(fields=['artist', 'category'], name='services_se_artist__35c3ce_idx'), models.Index(fields=['-booking_count'], name='services_se_booking_12d0a1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('duration__gte', 15), ('duration__lte', 480)), name='service_duration_valid_range'),
        ),
    ]
