# Generated by Django 5.0.1 on 2026-02-18 23:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_index=True, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Review comment from client')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Controls if review is publicly visible')),
                ('flagged', models.BooleanField(db_index=True, default=False, help_text='Flagged for moderation (spam/inappropriate content)')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason for flagging', null=True)),
                ('artist_response', models.TextField(blank=True, help_text="Artist's response to the review", null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When artist responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='profiles.makeupartistprofile')),
                ('booking', models.OneToOneField(help_text='The completed booking being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
