# Generated by Django 5.0.1 on 2026-02-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['artist', 'is_visible', '-created_at'], name='reviews_rev_artist__b085c5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client', '-created_at'], name='reviews_rev_client__5e5e56_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='reviews_rev_rating_6e3aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['flagged', 'is_visible'], name='reviews_rev_flagged_a703b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range'),
        ),
    ]
