# Generated by Django 5.0.1 on 2026-02-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='profiles.makeupartistprofile'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', '-created_at'], name='payments_pa_client__ef8bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['artist', 'status', '-created_at'], name='payments_pa_artist__d05456_idx'),
        ),
    ]
